version: '3.9'

services:
  acsite:
    container_name: ac-site
    image: ac-site_app:latest
    stdin_open: true
    build:
      context: ../site/
      dockerfile: ./dev.Dockerfile
    networks:
      - ac_net
    volumes:
      - ../site/project/components:/opt/app/components
      - ../site/project/libs:/opt/app/libs
      - ../site/project/pages:/opt/app/pages
      - ../site/project/public:/opt/app/public
      - ../site/project/models:/opt/app/models
      - ../site/project/utils:/opt/app/utils
      - ../site/project/helpers:/opt/app/helpers
      - ../site/project/jsconfig.json:/opt/app/jsconfig.json
      - ../site/project/next.config.js:/opt/app/next.config.js
      - ../site/project/package.json:/opt/app/package.json
      - site_node_modules:/opt/app/node_modules
      - site_next_dir:/opt/app/.next
      - site_out:/opt/app/out
    environment:
      - DATASETS_LINK=${DATASETS_LINK}
    entrypoint: ["/bin/sh","-c"]
    command: 
      - |
        ./download.sh > /opt/app/models/datasets.json
        npm run build:prod
        sh
networks:
  ac_net:

volumes:
  site_node_modules:
  # Volume used to store Next.js build artifacts:
  site_next_dir:
  site_out:
