version: '3.9'

services:
  acsite:
    container_name: ac-site
    image: ac-site_app:latest
    stdin_open: true
    build:
      context: ../site/
      dockerfile: ./dev.Dockerfile
    networks:
      - ac_net
    volumes:
      - site_node_modules:/opt/app/node_modules
      - site_next_dir:/opt/app/.next
      - site_out:/opt/app/out
    environment:
      - ALGAE_DATASETS_LINK=${ALGAE_DATASETS_LINK}
      - SHELLFISH_DATASETS_LINK=${SHELLFISH_DATASETS_LINK}
    entrypoint: ["/bin/sh","-c"]
    command: 
      - |
        ./download.sh $ALGAE_DATASETS_LINK /opt/app/models/algae_datasets.json A
        ./download.sh $SHELLFISH_DATASETS_LINK /opt/app/models/shellfish_datasets.json S
        cp /opt/app/models/algae_datasets.json /opt/app/public/_algae_datasets.json
        cp /opt/app/models/shellfish_datasets.json /opt/app/public/_shellfish_datasets.json
        npm run build:prod
networks:
  ac_net:

volumes:
  site_node_modules:
  # Volume used to store Next.js build artifacts:
  site_next_dir:
  site_out:
