version: '3.9'

services:
  acproxy:
    container_name: ac-proxy
    image: ac-proxy_app:latest
    stdin_open: true
    build:
      context: ../
      dockerfile: ./proxy/dev.Dockerfile
      args:
        WITH_UTILS: "true"
        NODE_HOST: "$NODE_HOST"
    ports:
      - "$HTTP_PORT:80"
      - "$HTTPS_PORT:443"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    networks:
      - ac_net
    depends_on:
      - acdashboard
      - acsite
    volumes:
      - site_out:/usr/share/nginx/html/

networks:
  ac_net:

volumes:
  site_out:

# TODO Try using similar settings so that the application network does not interfere with the adwiseeo network
# networks:
#   <network name>:
#     ipam:
#       config:
#         - subnet: 172.22.0.0/24

# services:
#   <service name>:
#     container_name: ...
#     networks:
#       <network name>:
#         ipv4_address: 172.22.0.2
