version: '3.9'

services:
  acproxy:
    container_name: ac-proxy
    stdin_open: true
    build:
      context: ../
      dockerfile: ./proxy/dev.Dockerfile
      args:
        WITH_UTILS: "true"
    ports:
      - "$HTTP_PORT:80"
      - "$HTTPS_PORT:443"
    networks:
      - ac_net
    depends_on:
      - acdashboard
      - acsite
    volumes:
      - site_out:/usr/share/nginx/html/

networks:
  ac_net:

volumes:
  site_out:
